### ISSUE TITLE
Create Unit Conversion API Documentation

### ISSUE THREAD

**Issue by artkapl** [PixelGoogs/SLM_Unit_Conversion_API#6]
Documentation is in a .docx document (found in [comment below](https://github.com/PixelGoogs/SLM_Unit_Conversion_API/issues/6#issuecomment-967001886))

**Comment by PixelGoogs** [comment]
[Unit Conversion API Dokumentation.docx](https://github.com/PixelGoogs/SLM_Unit_Conversion_API/files/7526921/Unit.Conversion.API.Dokumentation.docx)

**Comment by artkapl** [comment]
[Unit.Conversion.API.Dokumentation_2.docx](https://github.com/PixelGoogs/SLM_Unit_Conversion_API/files/7734378/Unit.Conversion.API.Dokumentation_2.docx)

Added screenshot for Interface issue

**Comment by artkapl** [comment]
[Unit.Conversion.API.Dokumentation_3.docx](https://github.com/PixelGoogs/SLM_Unit_Conversion_API/files/7734583/Unit.Conversion.API.Dokumentation_3.docx)

Added conversion interface in its own branch and pull request from feature branch to dev

**Comment by PixelGoogs** [comment]
[Unit.Conversion.API.Dokumentation_4.docx](https://github.com/PixelGoogs/SLM_Unit_Conversion_API/files/8002414/Unit.Conversion.API.Dokumentation_4.docx)
added merge and latest push

**Comment by artkapl** [comment]
[Unit.Conversion.API.Dokumentation_5.docx](https://github.com/PixelGoogs/SLM_Unit_Conversion_API/files/8096372/Unit.Conversion.API.Dokumentation_5.docx)

Added possible POST Request route for unit conversion to UnitConversionController (see 120e86482cdbe71ed157d14757f227437da5f251)

**Comment by artkapl** [comment]
[Unit.Conversion.API.Dokumentation_6.docx](https://github.com/PixelGoogs/SLM_Unit_Conversion_API/files/8185035/Unit.Conversion.API.Dokumentation_6.docx)

Implemented Strategy Pattern, removed model classes, updated controller, merged features to dev.

**Comment by PixelGoogs** [comment]
[Unit.Conversion.API.Dokumentation_7.docx](https://github.com/PixelGoogs/SLM_Unit_Conversion_API/files/8224298/Unit.Conversion.API.Dokumentation_7.docx)

Implemenented tests, started github pipeline working on artefact.

**Comment by PixelGoogs** [comment]
[Unit.Conversion.API.Dokumentation_8.docx](https://github.com/PixelGoogs/SLM_Unit_Conversion_API/files/8230639/Unit.Conversion.API.Dokumentation_8.docx)

Implemented final stages of project, pipeline, artefacts and still added JSON request and respsonse
Project basically complete, documentation will still be reviewed by team

**Comment by Racialist** [comment]
Approved documentation!

**Comment by PixelGoogs** [comment]
[Unit.Conversion.API.Dokumentation_9.docx](https://github.com/PixelGoogs/SLM_Unit_Conversion_API/files/8231243/Unit.Conversion.API.Dokumentation_9.docx)

added API Test

**Comment by artkapl** [comment]
[Unit.Conversion.API.Dokumentation_10.docx](https://github.com/PixelGoogs/SLM_Unit_Conversion_API/files/8232498/Unit.Conversion.API.Dokumentation_10.docx)

Added more integration tests and corresponding user story

**Comment by artkapl** [comment]
[Unit.Conversion.API.Dokumentation_11.docx](https://github.com/PixelGoogs/SLM_Unit_Conversion_API/files/8244713/Unit.Conversion.API.Dokumentation_11.docx)

Deleted feature branches and added branch log view

**Comment by artkapl** [comment]
Submitted PDF based on version 11 to Moodle --> Issue successfully completed & closed.
